name: Docker Image CI (to Aliyun)
on:
  #  push:
  #    branches:
  #      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: Login Aliyun
        run: |
          # 登录阿里云镜像仓库
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} ${{ secrets.DOCKER_REGISTRY }}

      - name: Build the Docker image
        run: |
          # 使用Dockerfile构建镜像
          docker build . --tag ${{ secrets.DOCKER_IMAGE_TAG }}

      - name: Push the Docker image
        run: |
          # 推送镜像到镜像仓库
          docker push ${{ secrets.DOCKER_IMAGE_TAG }}
